tests: fix race in test_max_whiteboard
This test keeps failing because WebDriver clicks the whiteboard before
the page reloads. We should only filter the whiteboards if the one we
want isn't already on the page, thus there should be no way WebDriver
can click it prematurely.

======================================================================
ERROR: test_max_whiteboard (bkr.inttest.server.selenium.test_job_matrix.TestJobMatrixWebDriver)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/bkr/inttest/server/selenium/test_job_matrix.py", line 53, in test_max_whiteboard
    b.find_element_by_xpath("//select[@name='whiteboard']/option[@value='%s']" % whiteboard).click()
  File "/usr/lib64/python2.6/site-packages/selenium/webdriver/remote/webelement.py", line 52, in click
    self._execute(Command.CLICK_ELEMENT)
  File "/usr/lib64/python2.6/site-packages/selenium/webdriver/remote/webelement.py", line 205, in _execute
    return self._parent.execute(command, params)
  File "/usr/lib64/python2.6/site-packages/selenium/webdriver/remote/webdriver.py", line 156, in execute
    self.error_handler.check_response(response)
  File "/usr/lib64/python2.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 147, in check_response
    raise exception_class(message, screen, stacktrace)
StaleElementReferenceException: Message: u'Element not found in the cache - perhaps the page has changed since it was looked up'

Also cleaned up a few other things related to whiteboard filtering in
the tests.

Change-Id: I634641afe3dc7957aa3ea4ce2f5036e6184a3986