roll back creation of VirtResource if VM creation fails
Otherwise the VirtResource row will be committed even though the VM was
never created and the recipe was not moved to Scheduled. So it will end
up breaking later on, when queued_recipes tries to provision a real
system for it:

    2012-11-12 18:12:12,071 beakerd ERROR Failed to commit in queued_recipes
    Traceback (most recent call last):
      File "/usr/lib/python2.6/site-packages/bkr/server/tools/beakerd.py", line 391, in queued_recipes
        recipe.resource.allocate()
      File "/usr/lib/python2.6/site-packages/bkr/server/model.py", line 5964, in allocate
        reservation_type=u'recipe')
      File "/usr/lib/python2.6/site-packages/bkr/server/model.py", line 2452, in reserve
        session.flush()
      [...]
    IntegrityError: (IntegrityError) (1452, 'Cannot add or update a child row: a foreign key constraint fails (`beaker_devel/recipe_resource`, CONSTRAINT `recipe_resource_recipe_id_fk` FOREIGN KEY (`recipe_id`) REFERENCES `recipe` (`id`) ON DELETE CASCADE ON UPDATE CASCADE)') 'UPDATE recipe_resource SET recipe_id=%s WHERE recipe_resource.id = %s' (None, 12L)

Change-Id: I6e9cd94ad674549e3dff688e5d2d8be0e9426fb5