tests: fix race condition in reserve workflow tree selection
Changing the distro selection re-populates the distro_tree_id select,
but this test could end up loading the options before they have been
re-populated, resulting in a failure like this:

    Traceback (most recent call last):
      File "/usr/lib/python2.7/site-packages/bkr/inttest/server/selenium/test_reserve_system.py", line 77, in test_no_lab_controller_distro
	self.assert_(not any('i386' in option.text for option in options), options)
    [...]
    StaleElementReferenceException: Message: Element not found in the cache - perhaps the page has changed since it was looked up

Change-Id: I6eb7fa48570ab5bf8da565241887ec6a90c03860