tests: fix race in test_system_loan
The test_return_loan case was intermittently failing like this:

    FAIL: bkr.inttest.server.selenium.test_system_loan:SystemLoanTest.test_return_loan
      /usr/bin/vim +81 src/bkr/inttest/server/selenium/test_system_loan.py  # test_return_loan
        self.assertEqual(sys_activity_name.old_value, u'admin')
    AssertionError: u'' != u'admin'

because the test was inspecting the database before the HTTP request to return
the loan was completed. The fix is to wait for the web UI to indicate the loan
was returned before looking in the db.

Change-Id: I7993e399d4e9eb7b41391fde999520b5c8bdb7d8