sqlalchemy 1.0 compatibility: cannot delete from join
With sqlalchemy 1.0, deleting from a query containing a join is now an
error. This fixes a failure in the tests for removing lab controllers:

    bkr.server ERROR Exception on /labcontrollers/lab249.testdata.invalid [PATCH]
    Traceback (most recent call last):
    [...]
      File "Server/bkr/server/labcontroller.py", line 151, in update_labcontroller
        remove_labcontroller(labcontroller)
      File "Server/bkr/server/labcontroller.py", line 92, in remove_labcontroller
        distro_tree_assocs.delete(synchronize_session=False)
      File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/query.py", line 3047, in delete
        self, synchronize_session)
      File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 1302, in factory
        }, synchronize_session, query)
      File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 1122, in _factory
        return klass(*arg)
      File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 1294, in __init__
        super(BulkDelete, self).__init__(query)
      File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 1087, in __init__
        self._validate_query_state()
      File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 1105, in _validate_query_state
        (methname, )
    InvalidRequestError: Can't call Query.update() or Query.delete() when join(), outerjoin(), select_from(), or from_self() has been called

OpenStack 11 provides sqlalchemy 1.0.

Change-Id: Ib09439d121fe41d2ad49103c7f11b816567c0afa