tests: wait for search bar animations to finish
The distro search and distro tree search tests were intermittently failing
because WebDriver would sometimes try to click on the Search button while it
was still animating. The click would be missed and the search would never be
performed. The solution is to wait for the animation to complete before trying
to interact with the page.

While investigating the problem I also took the opportunity to clean up the
tests a little.

    ======================================================================
    ERROR: test_search_distrotree (bkr.inttest.server.selenium.test_distro_trees.DistroTreeSearch)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/usr/lib/python2.6/site-packages/bkr/inttest/server/selenium/test_distro_trees.py", line 234, in test_search_distrotree
        % self.distro_one.name)
      File "/usr/lib64/python2.6/site-packages/selenium/webdriver/remote/webdriver.py", line 213, in find_element_by_xpath
        return self.find_element(by=By.XPATH, value=xpath)
      File "/usr/lib64/python2.6/site-packages/selenium/webdriver/remote/webdriver.py", line 671, in find_element
        {'using': by, 'value': value})['value']
      File "/usr/lib64/python2.6/site-packages/selenium/webdriver/remote/webdriver.py", line 156, in execute
        self.error_handler.check_response(response)
      File "/usr/lib64/python2.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 147, in check_response
        raise exception_class(message, screen, stacktrace)
    NoSuchElementException: Message: 'Message: u\'Unable to locate element: {"method":"xpath","selector":"//table[@id=\\\\"widget\\\\"]//td/a[text()=\\\\"nametest469\\\\"]"}\'

Change-Id: I0715c99ca09758c1ad4576cd39c54098ec4cf256