tests: lsof moved to /usr/bin in recent Fedora
Fixes this failure with the tests:

    ======================================================================
    ERROR: test suite for <module 'bkr.inttest' from '/usr/lib/python2.7/site-packages/bkr/inttest/__init__.pyc'>
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/usr/lib/python2.7/site-packages/nose/suite.py", line 209, in run
	self.setUp()
      File "/usr/lib/python2.7/site-packages/nose/suite.py", line 292, in setUp
	self.setupContext(ancestor)
      File "/usr/lib/python2.7/site-packages/nose/suite.py", line 315, in setupContext
	try_run(context, names)
      File "/usr/lib/python2.7/site-packages/nose/util.py", line 471, in try_run
	return func()
      File "/usr/lib/python2.7/site-packages/bkr/inttest/__init__.py", line 431, in setup_package
	process.start()
      File "/usr/lib/python2.7/site-packages/bkr/inttest/__init__.py", line 180, in start
	self._wait_for_listen(self.listen_port)
      File "/usr/lib/python2.7/site-packages/bkr/inttest/__init__.py", line 190, in _wait_for_listen
	if check_listen(self.listen_port):
      File "/usr/lib/python2.7/site-packages/bkr/inttest/__init__.py", line 134, in check_listen
	stdout=subprocess.PIPE, stderr=subprocess.PIPE).communicate()
      File "/usr/lib64/python2.7/subprocess.py", line 394, in __init__
	errread, errwrite)
      File "/usr/lib64/python2.7/subprocess.py", line 1047, in _execute_child
	raise child_exception
    OSError: [Errno 2] No such file or directory

Change-Id: I3cb75e16b2036584d9670e2439b5eb756d147b8b