tests: fix timing issue with recipe page refresh
The recipe page automatically re-fetches its state every 30 seconds. So
the test needs to wait slightly *more* than 30 seconds, otherwise there
is a chance it will start looking at the page while it's being
refreshed, leading to failures like this:

    ======================================================================
    ERROR: test_page_updates_itself_while_recipe_is_running (bkr.inttest.server.selenium.test_recipes.TestRecipeView)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/usr/lib/python2.6/site-packages/bkr/inttest/server/selenium/test_recipes.py", line 147, in test_page_updates_itself_while_recipe_is_running
	b.find_element_by_xpath('//div[@class="recipe-summary"]/p[1]').text,
    [...]
    StaleElementReferenceException: Message: Element not found in the cache - perhaps the page has changed since it was looked up

40 seconds should be a generous amount (30 seconds polling interval + 10
seconds for the request to finish which is the maximum we allow in
general in WebDriver tests).

Change-Id: Idf6eb179d956f6a3aa62baebe2d765cae4387ba2