fix server API docs build
python-netaddr was missing from BuildRequires:

    Traceback (most recent call last):
      File "/usr/lib/python2.6/site-packages/Sphinx-1.0.8-py2.6.egg/sphinx/ext/autodoc.py", line 329, in import_object
        __import__(self.modname)
      File "/builddir/build/BUILD/beaker-0.9.3/Server/bkr/server/systems.py", line 10, in <module>
        from bkr.server.kickstart import generate_kickstart
      File "/builddir/build/BUILD/beaker-0.9.3/Server/bkr/server/kickstart.py", line 6, in <module>
        import netaddr
    ImportError: No module named netaddr

Also fixed the Makefile so that build failures are actually reported(!)

Change-Id: Idb6689679181251e9a822c8da115ba2443a85870