tests: create task library snapshots in basepath.repos
We can't unconditionally use /tmp for task library snapshots in the
tests, because basepath.rpmspath might be on /var which might be
a separate filesystem.

Specifically, this fixes the following failure when tmpfs is mounted in
/tmp:

    Traceback (most recent call last):
      File "/usr/lib/python2.6/site-packages/bkr/server/tests/test_model.py", line 193, in test_make_snapshot_repo
        self.tasklibrary.make_snapshot_repo(recipe_repo_parent)
      File "/usr/lib/python2.6/site-packages/bkr/server/model/tasklibrary.py", line 175, in make_snapshot_repo
        self._link_rpms(repo_dir)
      File "/usr/lib/python2.6/site-packages/bkr/server/model/tasklibrary.py", line 158, in _link_rpms
        os.link(srcpath, dstpath)
    OSError: [Errno 18] Invalid cross-device link

Change-Id: I2db2d05ca902972de6e9a5f72d1435674a74aa9a