sys.exc_type and sys.exc_value are not thread-safe
These have been deprecated since Python 1.5 and should be replaced with
sys.exc_info() which returns the right values for the current thread.
This is to fix intermittent test failures like this:

  File "Server/bkr/server/xmlrpccontroller.py", line 69, in RPC2
      response = xmlrpclib.dumps(
  AttributeError: 'module' object has no attribute 'exc_value'

Change-Id: I693b039f2b4d329454e9d3a2543934f0505e0cb8