skip log-delete tests if kerberos is not available
We only support Kerberos authentication in log-delete, so we can just
skip the tests if it's missing.

    Traceback (most recent call last):
      File "/usr/lib/python2.6/site-packages/bkr/inttest/server/tools/test_log_delete.py", line 116, in test_log_delete_expired
        log_delete.log_delete()
      File "/usr/lib/python2.6/site-packages/bkr/server/tools/log_delete.py", line 54, in log_delete
        auth=requests.auth.HTTPKerberosAuth(require_mutual_auth=False))
      File "/usr/lib/python2.6/site-packages/requests/auth.py", line 279, in __init__
        raise Exception("Kerberos libraries unavailable")
    Exception: Kerberos libraries unavailable

Change-Id: I55a50aedbd1255545126101ad88f713a25b04454