even more targetted re-rendering of the recipe reservation tab
Commit 86686335 reduced the number of re-renders for parts of the
Reservation tab, however in this particular case (when the recipe is
Reserved and the RecipeRunningReservation view is shown) it was still
re-rendering once per second as the time_remaining_seconds counted down.

The template doesn't actually care about the number of seconds
remaining, only whether it's greater than zero, so we can make our
listening a bit more selective.

This should fix a timing issue in the tests (as well as being nicer for
human users as well):

    ======================================================================
    ERROR: test_authenticated_user_can_return_reservation (bkr.inttest.server.selenium.test_recipes.TestRecipeViewReservationTab)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/usr/lib/python2.6/site-packages/bkr/inttest/server/selenium/test_recipes.py", line 1017, in test_authenticated_user_can_return_reservation
	tab.find_element_by_xpath('.//button[contains(text(), "Return the reservation")]')\
      File "/usr/lib64/python2.6/site-packages/selenium/webdriver/remote/webelement.py", line 74, in click
	self._execute(Command.CLICK_ELEMENT)
      File "/usr/lib64/python2.6/site-packages/selenium/webdriver/remote/webelement.py", line 457, in _execute
	return self._parent.execute(command, params)
      File "/usr/lib64/python2.6/site-packages/selenium/webdriver/remote/webdriver.py", line 233, in execute
	self.error_handler.check_response(response)
      File "/usr/lib64/python2.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
	raise exception_class(message, screen, stacktrace)
    StaleElementReferenceException: Message: Element not found in the cache - perhaps the page has changed since it was looked up

Change-Id: I4ef4b8969266a712751a396eabcb11e8485e4ea7