more targetted re-rendering for Reservation tab
Currently the tab is re-rendering itself any time anything in the recipe
changes (which is very often). We can listen to more specific change
events instead.

This also fixes a timing issue in the tests, which can fail like this
because the Reservation tab ends up re-rendering itself again for no
reason *after* the Edit Reservation modal is closed.

    ERROR: test_authenticated_user_can_request_reservation (bkr.inttest.server.selenium.test_recipes.TestRecipeViewReservationTab)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/usr/lib/python2.7/site-packages/bkr/inttest/server/selenium/test_recipes.py", line 869, in test_authenticated_user_can_request_reservation
	self.assertEqual(tab.find_element_by_xpath('div/p').text,
      File "/usr/lib64/python2.7/site-packages/selenium/webdriver/remote/webelement.py", line 70, in text
	return self._execute(Command.GET_ELEMENT_TEXT)['value']
      File "/usr/lib64/python2.7/site-packages/selenium/webdriver/remote/webelement.py", line 457, in _execute
	return self._parent.execute(command, params)
      File "/usr/lib64/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 233, in execute
	self.error_handler.check_response(response)
      File "/usr/lib64/python2.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
	raise exception_class(message, screen, stacktrace)
    StaleElementReferenceException: Message: Element not found in the cache - perhaps the page has changed since it was looked up

Change-Id: I61baca25a5a188b814cf94d06a0c07a2d255c40d