test_system_loan: wait for loan modal to close
This was failing with newer WebDriver because of some extra sanity
checks, complaining that we were clicking on a menu covered by the modal
backdrop:

    WebDriverException: Message: Element is not clickable at point (1683, 20). Other element would receive the click: <div class="modal-backdrop  in"></div>

Change-Id: Iff9adc0be56a4b07cde3776f48f7f17a5082673e