beaker-refresh-ldap fails - user lacks email addr
Some Beaker installations learns user via ldap groups.  One user
did not have an email address resulting in beaker-refresh-ldap
raising an exception:
KeyError: 'mail'. Offending line is here:
  File "/usr/lib/python2.7/site-packages/bkr/server/model/identity.py",
       line 301, in by_user_name
    user.email_address = attrs['mail'][0].decode('utf8')
KeyError: 'mail'
When this exception is encountered, beaker-refresh-ldap stops learning other users.
Fix: When missing any required key attributes (Mail, uid, cn), the user will
not be returned and as a result will not be learned without raising an exception.
This allows beaker-refresh-ldap to continue learning other users.