tests: fix timing issue with comment text
Trying to avoid intermittent failures like this one:

    Traceback (most recent call last):
      File "/usr/lib/python2.6/site-packages/bkr/inttest/server/selenium/test_jobs.py", line 579, in test_html_in_comments_is_escaped
	self.assertEqual(comment_paragraph.text, bad_comment)
    AssertionError: u'' != '<script>alert("xss")</script>'

which I suspect are happening because WebDriver is grabbing the text
content of the p while the comments view is still rendering itself.

Change-Id: I600e5a330e929268a618f7eff80218bbe8f07f81