recipe_task_result.recipe_task_id should be non-NULLable
This patch also refactors the setup in test_task_search. Previously
these test cases were creating and then deleting task rows, which in one
case would leave behind orphaned recipe_task_result rows which are now
(correctly) prevented.

    IntegrityError: (IntegrityError) (1452, 'Cannot add or update a child row: a foreign key constraint fails (`beaker_test`.`recipe_task_result`, CONSTRAINT `recipe_task_result_ibfk_1` FOREIGN KEY (`recipe_task_id`) REFERENCES `recipe_task` (`id`))') 'UPDATE recipe_task_result SET recipe_task_id=%s WHERE recipe_task_result.id = %s' (None, 6L)

Bug: 1393186
Change-Id: Ibbfa819e7d0bfa734ce85ac244ac4c38f08c5aca