two-argument .join() is not accepted in sqlalchemy 0.7
    Traceback (most recent call last):
      File "src/bkr/inttest/server/test_kickstart.py", line 1020, in test_beaker_url
        ''', self.system)
      File "src/bkr/inttest/server/test_kickstart.py", line 272, in provision_recipe
        recipe.provision()
      File "../Server/bkr/server/model.py", line 5118, in provision
        .combined_with(self.generated_install_options())\
      File "../Server/bkr/server/model.py", line 4699, in generated_install_options
        'packages': ':'.join(p.package for p in self.packages),
      File "../Server/bkr/server/model.py", line 4805, in _get_packages
        .select_from(RecipeTask).join(Task, Task.required)
      File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/query.py", line 1638, in join
        from_joinpoint=from_joinpoint)
      File "<string>", line 1, in <lambda>
      File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/query.py", line 50, in generate
        fn(self, *args[1:], **kw)
      File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/query.py", line 1767, in _join
        outerjoin, create_aliases, prop)
      File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/query.py", line 1791, in _join_left_to_right
        prop)
      File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/query.py", line 1820, in _prepare_right_side
        "the right side of join condition %s" % (right, onclause)
    InvalidRequestError: Join target <class 'bkr.server.model.Task'> does not correspond to the right side of join condition Task.required

Change-Id: I750418194fee6f685e31e4f4c8f0ac010ca469d1