tests: fix timing issue with power types bootstrap-growl errors
The bootstrap-growl error div sometimes comes back with empty text if
WebDriver catches it at exactly the wrong moment, resulting in errors
like this:

    Traceback (most recent call last):
      File "/usr/lib/python2.6/site-packages/bkr/inttest/server/selenium/test_power_types.py", line 81, in test_errors_when_deleting_referenced_power_type
        'Power type %s.*.still referenced' % power_type.name)
    AssertionError: Regex didn't match: u'Power type ilo.*.still referenced' not found in u''

We have run into this before, we need to assert the error message as
part of the XPath for bootstrap-growl errors to avoid this timing
problem.

Change-Id: Ic11e67ac43fc76a93ce8e222fa50eafe527b6ea5