fix watchdog death if console log does not exist
The beaker-watchdog daemon dies with a traceback like:

Traceback (most recent call last):
  File "/usr/bin/beaker-watchdog", line 9, in <module>
    load_entry_point('bkr.labcontroller==0.9.0', 'console_scripts', 'beaker-watchdog')()
  File "/usr/lib/python2.6/site-packages/bkr/labcontroller/watchdog.py", line 159, in main
    main_loop(conf=conf, foreground=True)
  File "/usr/lib/python2.6/site-packages/bkr/labcontroller/watchdog.py", line 118, in main_loop
    if not watchdog.run():
  File "/usr/lib/python2.6/site-packages/bkr/labcontroller/proxy.py", line 419, in run
    updated |= monitor.run()
TypeError: unsupported operand type(s) for |=: 'bool' and 'NoneType'