Drop the index first before dropping the colum
MariaDB 10 now requires us to drop the index first, before dropping the column.
Otherwise the column drop will result in:

    OperationalError: (_mysql_exceptions.OperationalError) (1072, "Key column 'fw_version' doesn't exist in table") [SQL: u'ALTER TABLE device DROP COLUMN fw_version']

Change-Id: Ib07d09f86394912f7a9e511df8b649cc17f76fbe